spring:
  profiles:
    #  开发过程中，请将 travis 修改为 dev
    active: ${active:travis}

  jpa:
    hibernate:
      ddl-auto: create
  session:
    store-type: JDBC

  # 禁用SpringSecurity的Session存储
  security:
    sessions: never

logging:
  path: logs/
  file: ./logs.log
  level:
    root: info
    club:
      yunzhi:
        log: info
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: info
server:
  port: ${port:8114}

---
# 机器人环境
spring:
  profiles: travis

---
# 开发环境
spring:
  profiles: dev
debug: true

---
# 生产环境
spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    #    数据库名称关系到数据库迁移
    url: jdbc:mysql://${datasource.url:127.0.0.1}:${datasource.port:3306}/${datasource.dbname:log}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${datasource.username:root}
    password: ${datasource.password:}
    separator: //
  flyway:
    enabled: true # 禁用baseline

---
# 调试环境
spring:
  profiles: debug
debug: true
